server:
  port: 9098

spring:
  application:
    name: rabbitmq-begin

  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG
